### PR TITLE
Hotfix 1.13.1

### PR DESCRIPTION
**Pull request by rderocle**

### CODE REVIEW

**Comment by geoffroy-aubry** [comment]
All OK on Ubuntu.

On Mac OS X 10.9.2:
- OK for twgit-dist.sh
- ERROR: 

``` bash
bash-4.2$ stat --printf='%Y\n' test
stat: illegal option -- -
usage: stat [-FlLnqrsx] [-f format] [-t timefmt] [file ...]
```
- ERROR:

``` bash
bash-4.2$ date --date="@1393945123" +"%Y-%m-%d %T"
date: illegal option -- -
usage: date [-jnu] [-d dst] [-r seconds] [-t west] [-v[+|-]val[ymwdHMS]] ... 
            [-f fmt date | [[[mm]dd]HH]MM[[cc]yy][.ss]] [+format]
```

:-/

**Comment by rderocle** [comment]
Yep, actually I installed some utils functions in macos using brew.
It could be a prerequisite (same as bash 4)....

$> brew install coreutils findutils gnu-tar gnu-sed gawk gnutls gnu-indent gnu-getopt

I have to find a way to know which parameters to use in this particular case.

**Comment by geoffroy-aubry** [comment]
What can we do with this issue?

**Comment by rderocle** [comment]
I think we can close it. the feature 127 fixed everything I think :)

**Pull request closed without merging**
