### PR TITLE
Feature/hotfix/jira

### PR DESCRIPTION
**Pull request by oversanne**
There is an issue using python. Sometimes in jira it doesn't interprete correctly return of jira api. But in PHP it works.

I propose this quick ugly hotfix, and I propose to use curl instead of wget.

### CODE REVIEW

**Comment by geoffroy-aubry** [comment]
Sorry, it's too ugly ;-)
Currently only `wget` availability is tested in `assert_connectors_well_configured()` function in `inc/common.inc.sh`. Add `curl` will be excessive…
You must find a value misinterpreted by Jira connector to reproduce the bug :-/

**Comment by oversanne** [comment]
echo $data | python -c "import json,sys;s=sys.stdin.read();s=s.replace('\r\n', '');s=json.loads(s);print s['fields']['summary'];" 2>~/www/twgit/.history.error

gives:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 45: ordinal not in range(128)
Traceback (most recent call last):
  File "<string>", line 1, in <module>
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 1: ordinal not in range(128)
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site.py", line 62, in <module>
    import os
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 398, in <module>
    import UserDict
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/UserDict.py", line 1, in <module>
    """A more or less complete user-defined wrapper around dictionary objects."""
KeyboardInterrupt

**Comment by oversanne** [comment]
I change encoding. PR update. Could you check?

**Comment by oversanne** [comment]
This solved my problem, and now it works fine :)

**Comment by geoffroy-aubry** [comment]
It's not the solution to convert into ASCII… Some characters will be unreadable.

I read the code of Jira connector and I realize his author went a bit too fast :-/
- eval unnecessary
- 2>/dev/null for python but dropped for PHP
- UTF-8 support present in other connectors but not here

I open a hotfix and ask you for validation.
Thanks for your perseverance ^^

**Comment by oversanne** [comment]
Ok thanks :)

**Comment by ghost** [comment]
Still boggy on my side. Any progress ?

**Pull request closed without merging**
